/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Modelclass.Admin;
import Modelclass.AdminDirectory;

/**
 *
 * @author dell
 */
public class AdminJPanel extends javax.swing.JPanel {
    private AdminDirectory adminDirectory;
    private JPanel workArea;
    /**
     * Creates new form AdminHighJPanel
     */
    public AdminJPanel(JPanel workArea, AdminDirectory adminDirectory) {
        initComponents();
        this.workArea=workArea;
        this.adminDirectory=adminDirectory;
        populateCourtDropdown();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AdminRolecmb = new javax.swing.JComboBox<>();

        jLabel1.setText("Username :");

        jLabel2.setText("Password : ");

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Admin Login");

        jLabel4.setText("Court :");

        AdminRolecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AdminRolecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRolecmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginbtn)
                            .addComponent(txtpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(AdminRolecmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AdminRolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(loginbtn)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
 String username = txtusername.getText();
    String password = txtpassword.getText();

    // Authenticate the user
    Admin admin = adminDirectory.authenticateUser(username, password);
    if (admin != null) {
        // Validate selected role from JComboBox
        if (AdminRolecmb.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a role to login.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String selectedRole = AdminRolecmb.getSelectedItem().toString();
        JPanel selectedPanel = null;

        // Navigate to the appropriate panel based on role
        if (selectedRole.equalsIgnoreCase("Supreme Court")) {
            selectedPanel = new AdminSupremeWorkAreaJPanel(workArea, admin);
            JOptionPane.showMessageDialog(this, "Login successful! Welcome to the Supreme Court Work Area.");
        } else if (selectedRole.equalsIgnoreCase("High Court")) {
            selectedPanel = new AdminHighWorkAreaJPanel(workArea, admin);
            JOptionPane.showMessageDialog(this, "Login successful! Welcome to the High Court Work Area.");
        } else {
            JOptionPane.showMessageDialog(this, "Please select role!" );
           
        }

        // Add and navigate to the selected panel
        workArea.add("WorkAreaJPanel", selectedPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    } else {
        // Display error if authentication fails
        JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void AdminRolecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRolecmbActionPerformed
//        AdminRolecmb.removeAllItems();
//        AdminRolecmb.addItem("Select");
//        AdminRolecmb.addItem("High Court");
//        AdminRolecmb.addItem("Supreme Court");
        if (AdminRolecmb.getSelectedItem() == null) return;

    // Populate the `adminRole` JComboBox with valid role options dynamically
    String selectedRole = AdminRolecmb.getSelectedItem().toString();
    
     
    }//GEN-LAST:event_AdminRolecmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AdminRolecmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
 private void populateCourtDropdown() {
        AdminRolecmb.removeAllItems();
        AdminRolecmb.addItem("Select");
        AdminRolecmb.addItem("High Court");
        AdminRolecmb.addItem("Supreme Court");
    }
}
