/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Modelclass.Admin;
import Modelclass.ClientDirectory;
import Modelclass.SPLawyerDirectory;

/**
 *
 * @author dell
 */
public class AdminSupremeWorkAreaJPanel extends javax.swing.JPanel {
    JPanel workArea;
    Admin admin;
    SPLawyerDirectory slawyerDirectory;
    ClientDirectory clientDirectory;
   
    
    /**
     * Creates new form AdminSupremeWorkAreaJPanel
     */
    public AdminSupremeWorkAreaJPanel(JPanel workArea, Admin admin) {
        initComponents();
        this.workArea = workArea;
        this.admin = admin;
        this.slawyerDirectory = new SPLawyerDirectory(); 
        this.clientDirectory=new ClientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lawyerbtn = new javax.swing.JButton();
        Clientbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lawyerbtn.setText("Lawyer");
        lawyerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lawyerbtnActionPerformed(evt);
            }
        });

        Clientbtn.setText("Client");
        Clientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Supreme Court Administration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clientbtn)
                            .addComponent(lawyerbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lawyerbtn)
                .addGap(71, 71, 71)
                .addComponent(Clientbtn)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lawyerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lawyerbtnActionPerformed
        // TODO add your handling code here:
        SPLawyerManagementJPanel panel= new SPLawyerManagementJPanel(workArea, slawyerDirectory);
        workArea.add("SPLawyerManagementJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_lawyerbtnActionPerformed

    private void ClientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientbtnActionPerformed
        // TODO add your handling code here:
        SPViewClientJPanel panel= new SPViewClientJPanel(workArea,clientDirectory);
        workArea.add("SPViewClientJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_ClientbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lawyerbtn;
    // End of variables declaration//GEN-END:variables
}
