/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HighCourtLawyer;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Modelclass.HCLawyerDirectory;
import Modelclass.SPLawyerDirectory;

/**
 *
 * @author dell
 */
public class LawyerJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private HCLawyerDirectory hlawyerDirectory;
    private SPLawyerDirectory slawyerDirectory ;
    /**
     * Creates new form LawyerJPanel
     */
    public LawyerJPanel(JPanel workArea) {
        initComponents();
        this.workArea=workArea;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highbtn = new javax.swing.JButton();
        supremebtn = new javax.swing.JButton();

        highbtn.setText("High Court");
        highbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highbtnActionPerformed(evt);
            }
        });

        supremebtn.setText("Supreme Court");
        supremebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supremebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(highbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(supremebtn)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(highbtn)
                .addGap(31, 31, 31)
                .addComponent(supremebtn)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void highbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highbtnActionPerformed
        // TODO add your handling code here:
        HCLawyerRegisterJPanel panel = new HCLawyerRegisterJPanel(workArea, hlawyerDirectory);
        workArea.add("HCLawyerRegisterJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_highbtnActionPerformed

    private void supremebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supremebtnActionPerformed
        // TODO add your handling code here:
        SPLawyerRegisterJPanel panel = new SPLawyerRegisterJPanel(workArea,slawyerDirectory);
        workArea.add("LawyerJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
                                  
    }//GEN-LAST:event_supremebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton highbtn;
    private javax.swing.JButton supremebtn;
    // End of variables declaration//GEN-END:variables
}
