/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HighCourtLawyer;

import Modelclass.ForensicReportDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Modelclass.SPLawyer;

/**
 *
 * @author dell
 */
public class SPLawyerWorkArea extends javax.swing.JPanel {
    JPanel workArea;
    SPLawyer spLawyer;
    ForensicReportDirectory forensicreportDirectory;
    /**
     * Creates new form HCLawyerWorkArea
     */
    public SPLawyerWorkArea(JPanel workArea, SPLawyer spLawyer) {
        initComponents();
        this.workArea=workArea;
        this.spLawyer=spLawyer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aptbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();

        aptbtn.setText("View Appointment");
        aptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptbtnActionPerformed(evt);
            }
        });

        reportbtn.setText("View Report");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptbtn))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(aptbtn)
                .addGap(55, 55, 55)
                .addComponent(reportbtn)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptbtnActionPerformed
        // TODO add your handling code here:
       SPViewAppointmentJPanel panel = new SPViewAppointmentJPanel(workArea);
        workArea.add("LawyerLoginJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_aptbtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        // TODO add your handling code here:
        SPViewReportJPanel panel = new SPViewReportJPanel(workArea, forensicreportDirectory);
        workArea.add("LawyerLoginJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_reportbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aptbtn;
    private javax.swing.JButton reportbtn;
    // End of variables declaration//GEN-END:variables
}
