/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HighCourtLawyer;

import Modelclass.HCLawyerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


import Modelclass.SPLawyer;
import Modelclass.SPLawyerDirectory;

/**
 *
 * @author dell
 */
public class SPLawyerRegisterJPanel extends javax.swing.JPanel {
   private JPanel workArea;
   private SPLawyer spLawyer;
// private SPLawyerDirectory slawyerDirectory;
    
SPLawyerDirectory slawyerDirectory = new SPLawyerDirectory();
    
    /**
     * Creates new form HCLawyerRegisterJPanel
     * @param workArea
     * @param slawyerDirectory
     */
    public SPLawyerRegisterJPanel(JPanel workArea, SPLawyerDirectory slawyerDirectory) {
        initComponents();
    this.workArea = workArea;
    if (slawyerDirectory == null) {
            this.slawyerDirectory = new SPLawyerDirectory(); // Initialize if null
        } else {
            this.slawyerDirectory = slawyerDirectory; // Use the passed directory
        } // Assign the passed directory
    populateLawyersDropdown();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtstateid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdfiled = new javax.swing.JPasswordField();
        txtname = new javax.swing.JTextField();
        lawyerRolecmb = new javax.swing.JComboBox<>();
        txtaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtconsulfee = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();

        jLabel3.setText("Registration Form");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Specialization :");

        jLabel1.setText("Central ID :");

        jLabel11.setText("Username:");

        jLabel12.setText("Password:");

        jLabel10.setText("Consultation Fee :");

        jLabel2.setText("Name :");

        lawyerRolecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lawyerRolecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lawyerRolecmbActionPerformed(evt);
            }
        });

        jLabel5.setText("Phone Number :");

        jLabel6.setText("Address :");

        jLabel4.setText("Email :");

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBack)
                .addGap(277, 277, 277)
                .addComponent(jLabel3)
                .addContainerGap(430, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lawyerRolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerbtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtstateid)
                                .addComponent(txtname)
                                .addComponent(txtconsulfee)
                                .addComponent(txtaddress)
                                .addComponent(phonenumber)
                                .addComponent(txtusername)
                                .addComponent(pwdfiled)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtstateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lawyerRolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtconsulfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pwdfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(registerbtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lawyerRolecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lawyerRolecmbActionPerformed
        //        AdminRolecmb.removeAllItems();
        //        AdminRolecmb.addItem("Select");
        //        AdminRolecmb.addItem("High Court");
        //        AdminRolecmb.addItem("Supreme Court");
        if (lawyerRolecmb.getSelectedItem() == null) return;

        // Populate the `adminRole` JComboBox with valid role options dynamically
        String selectedRole = lawyerRolecmb.getSelectedItem().toString();
    }//GEN-LAST:event_lawyerRolecmbActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
         try {
                   
            // Gather inputs
            String centralId = txtstateid.getText().trim();
            String name = txtname.getText().trim();
            String specialization = lawyerRolecmb.getSelectedItem().toString();
            String phoneNumber = phonenumber.getText().trim();
            String email = txtemail.getText().trim();
            String address = txtaddress.getText().trim();
            String username = txtusername.getText().trim();
            String password = new String(pwdfiled.getPassword());
            double consultationFee;

            // Input validation
            if (centralId.isEmpty() || name.isEmpty() || specialization.equals("Select") || phoneNumber.isEmpty()
                    || email.isEmpty() || address.isEmpty() || username.isEmpty() || password.isEmpty()) {
                throw new IllegalArgumentException("All fields are required.");
            }

            try {
                consultationFee = Double.parseDouble(txtconsulfee.getText().trim());
                if (consultationFee < 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Consultation fee must be a valid positive number.");
            }

            // Add lawyer to directory
            SPLawyer newLawyer = new SPLawyer(centralId, name, specialization, address, phoneNumber, email, consultationFee, username, password);
            slawyerDirectory.addLawyer(newLawyer);
            // Clear inputs
            
            // Success message
            JOptionPane.showMessageDialog(this, "Lawyer registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearField();
            SPLawyerLoginJPanel panel = new SPLawyerLoginJPanel(workArea,slawyerDirectory);
        workArea.add("LawyerLoginJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
            
          

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
//try {
//        // Gather inputs
//        String centralId = txtstateid.getText().trim();
//        String name = txtname.getText().trim();
//        String specialization = (String) lawyerRolecmb.getSelectedItem();
//        String phoneNumber = phonenumber.getText().trim();
//        String email = txtemail.getText().trim();
//        String address = txtaddress.getText().trim();
//        String username = txtusername.getText().trim();
//        String password = new String(pwdfiled.getPassword());
//        double consultationFee;
//
//        // Input validation
//        if (centralId.isEmpty() || name.isEmpty() || specialization.equals("Select") || phoneNumber.isEmpty() ||
//                email.isEmpty() || address.isEmpty() || username.isEmpty() || password.isEmpty()) {
//            throw new IllegalArgumentException("All fields are required.");
//        }
//
//        if (!phoneNumber.matches("\\d{10}")) {
//            throw new IllegalArgumentException("Phone number must be 10 digits.");
//        }
//
//        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
//            throw new IllegalArgumentException("Invalid email format.");
//        }
//
//        try {
//            consultationFee = Double.parseDouble(txtconsulfee.getText().trim());
//            if (consultationFee < 0) {
//                throw new NumberFormatException();
//            }
//        } catch (NumberFormatException e) {
//            throw new IllegalArgumentException("Consultation fee must be a valid positive number.");
//        }
//
//        // Check for duplicate username
//        SPLawyer existingLawyer = slawyerDirectory.searchLawyerByUsername(username);
//        if (existingLawyer != null) {
//            throw new IllegalArgumentException("Username already exists. Please choose a different username.");
//        }
//
//        // Add lawyer to directory
//        SPLawyer newLawyer = new SPLawyer(centralId, name, specialization, address, phoneNumber, email, consultationFee, username, password);
//        slawyerDirectory.addLawyer(newLawyer);
//
//        // Success message
//        JOptionPane.showMessageDialog(this, "Lawyer registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
//
//        // Clear fields
//        clearField();
//
//        // Navigate to login panel
//        SPLawyerLoginJPanel panel = new SPLawyerLoginJPanel(workArea, slawyerDirectory);
//        workArea.add("LawyerLoginJPanel", panel);
//        CardLayout layout = (CardLayout) workArea.getLayout();
//        layout.next(workArea);
//
//    } catch (IllegalArgumentException e) {
//        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }

    }//GEN-LAST:event_registerbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> lawyerRolecmb;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JPasswordField pwdfiled;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtconsulfee;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstateid;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
private void populateLawyersDropdown() {
        lawyerRolecmb.removeAllItems();
        lawyerRolecmb.addItem("Select");
        lawyerRolecmb.addItem("Criminal Lawyer");
        lawyerRolecmb.addItem("Civil Lawyer");
        lawyerRolecmb.addItem("Family Lawyer");
        lawyerRolecmb.addItem("Corporate Lawyer");
        
    }
  private void clearField() {
        txtstateid.setText("");
        txtname.setText("");
        lawyerRolecmb.setSelectedIndex(0);
        phonenumber.setText("");
        txtemail.setText("");
        txtaddress.setText("");
        txtconsulfee.setText("");
        txtusername.setText("");
        pwdfiled.setText("");
    }
}
