/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.client;

/**
 *
 * @author dell
 */
public class ClientRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientRegisterJPanel
     */
    public ClientRegisterJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdfiled = new javax.swing.JPasswordField();
        txtemail = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();

        jLabel2.setText("Name :");

        jLabel5.setText("Phone Number :");

        jLabel11.setText("Username:");

        jLabel6.setText("Address :");

        jLabel12.setText("Password:");

        jLabel4.setText("Email :");

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(registerbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(pwdfiled)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(251, 251, 251))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtaddress)
                            .addComponent(phonenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(246, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pwdfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(registerbtn)
                .addGap(85, 85, 85))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
        try {

            // Gather inputs
            String centralId = txtstateid.getText().trim();
            String name = txtname.getText().trim();
            String specialization = lawyerRolecmb.getSelectedItem().toString();
            String phoneNumber = phonenumber.getText().trim();
            String email = txtemail.getText().trim();
            String address = txtaddress.getText().trim();
            String username = txtusername.getText().trim();
            String password = new String(pwdfiled.getPassword());
            double consultationFee;

            // Input validation
            if (centralId.isEmpty() || name.isEmpty() || specialization.equals("Select") || phoneNumber.isEmpty()
                || email.isEmpty() || address.isEmpty() || username.isEmpty() || password.isEmpty()) {
                throw new IllegalArgumentException("All fields are required.");
            }

            try {
                consultationFee = Double.parseDouble(txtconsulfee.getText().trim());
                if (consultationFee < 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Consultation fee must be a valid positive number.");
            }

            // Add lawyer to directory
            SPLawyer newLawyer = new SPLawyer(centralId, name, specialization, address, phoneNumber, email, consultationFee, username, password);
            slawyerDirectory.addLawyer(newLawyer);
            // Clear inputs

            // Success message
            JOptionPane.showMessageDialog(this, "Lawyer registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearField();
            SPLawyerLoginJPanel panel = new SPLawyerLoginJPanel(workArea,slawyerDirectory);
            workArea.add("LawyerLoginJPanel", panel);
            CardLayout layout =(CardLayout) workArea.getLayout();
            layout.next(workArea);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        //try {
            //        // Gather inputs
            //        String centralId = txtstateid.getText().trim();
            //        String name = txtname.getText().trim();
            //        String specialization = (String) lawyerRolecmb.getSelectedItem();
            //        String phoneNumber = phonenumber.getText().trim();
            //        String email = txtemail.getText().trim();
            //        String address = txtaddress.getText().trim();
            //        String username = txtusername.getText().trim();
            //        String password = new String(pwdfiled.getPassword());
            //        double consultationFee;
            //
            //        // Input validation
            //        if (centralId.isEmpty() || name.isEmpty() || specialization.equals("Select") || phoneNumber.isEmpty() ||
                //                email.isEmpty() || address.isEmpty() || username.isEmpty() || password.isEmpty()) {
                //            throw new IllegalArgumentException("All fields are required.");
                //        }
            //
            //        if (!phoneNumber.matches("\\d{10}")) {
                //            throw new IllegalArgumentException("Phone number must be 10 digits.");
                //        }
            //
            //        if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                //            throw new IllegalArgumentException("Invalid email format.");
                //        }
            //
            //        try {
                //            consultationFee = Double.parseDouble(txtconsulfee.getText().trim());
                //            if (consultationFee < 0) {
                    //                throw new NumberFormatException();
                    //            }
                //        } catch (NumberFormatException e) {
                //            throw new IllegalArgumentException("Consultation fee must be a valid positive number.");
                //        }
            //
            //        // Check for duplicate username
            //        SPLawyer existingLawyer = slawyerDirectory.searchLawyerByUsername(username);
            //        if (existingLawyer != null) {
                //            throw new IllegalArgumentException("Username already exists. Please choose a different username.");
                //        }
            //
            //        // Add lawyer to directory
            //        SPLawyer newLawyer = new SPLawyer(centralId, name, specialization, address, phoneNumber, email, consultationFee, username, password);
            //        slawyerDirectory.addLawyer(newLawyer);
            //
            //        // Success message
            //        JOptionPane.showMessageDialog(this, "Lawyer registered successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            //
            //        // Clear fields
            //        clearField();
            //
            //        // Navigate to login panel
            //        SPLawyerLoginJPanel panel = new SPLawyerLoginJPanel(workArea, slawyerDirectory);
            //        workArea.add("LawyerLoginJPanel", panel);
            //        CardLayout layout = (CardLayout) workArea.getLayout();
            //        layout.next(workArea);
            //
            //    } catch (IllegalArgumentException e) {
            //        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //    }
    }//GEN-LAST:event_registerbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JPasswordField pwdfiled;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
