/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Client;

import Modelclass.Appointment;
import Modelclass.AppointmentDirectory;
import Modelclass.ClientDirectory;
import Modelclass.HCLawyerDirectory;
import Modelclass.SPLawyer;
import Modelclass.SPLawyerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lokes
 */
public class ClientSCLawyerJPanel extends javax.swing.JPanel {
private JPanel workArea;
private AppointmentDirectory appointmentDirectory;
       

//    private SPLawyerDirectory slawyerDirectory;
    
    /**
     * Creates new form LawyerManagementJPanel
     */
    SPLawyerDirectory slawyerDirectory = new SPLawyerDirectory();
    /**
     * Creates new form ClinetSCLawyerJPanel
     */
    public ClientSCLawyerJPanel(JPanel workArea,AppointmentDirectory appointmentDirectory,  SPLawyerDirectory slawyerDirectory) {
        initComponents();
        this.workArea = workArea;
        this.slawyerDirectory = slawyerDirectory;
         this.appointmentDirectory = appointmentDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aptbtn = new javax.swing.JButton();
        SCName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SCDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SCLawyer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SCPayment = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LawyerTbl = new javax.swing.JTable();

        aptbtn.setText("Book Appointment");
        aptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        jLabel4.setText("Lawyer");

        SCLawyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCLawyerActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment");

        jLabel1.setText("Supreme Court Lawyer");

        jLabel2.setText("Name");

        LawyerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Central ID", "Name", "Phone Number", "Email", "Office Address", "Consultation Fee"
            }
        ));
        jScrollPane1.setViewportView(LawyerTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(SCName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SCDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SCLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aptbtn)
                            .addComponent(SCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(SCLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aptbtn)
                .addGap(152, 152, 152))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptbtnActionPerformed
        // TODO add your handling code here:
         String name = SCName.getText();
        String date = SCDate.getText();
        String lawyerName = SCLawyer.getText();
        String payment = SCPayment.getText();

        if (name.isEmpty() || date.isEmpty() || lawyerName.isEmpty() || payment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.");
            return;
        }

        // Create a new Appointment object
        Appointment newAppointment = new Appointment();
        newAppointment.setName(name);
        newAppointment.setDate(date);
        newAppointment.setLawyer(lawyerName);
        newAppointment.setPayment(payment);

        // Add the appointment to the appointment directory
        appointmentDirectory.getAppointments().add(newAppointment);

        // Optionally, you can also update the table or show a success message
        JOptionPane.showMessageDialog(this, "Appointment booked successfully!");
        ClientFeedBackJPanel panel = new ClientFeedBackJPanel(workArea);
            workArea.add("ClientLoginJPanel", panel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        // Clear the input fields
        SCName.setText("");
        SCDate.setText("");
        SCLawyer.setText("");
        SCPayment.setText("");
    }//GEN-LAST:event_aptbtnActionPerformed

    private void SCLawyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCLawyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCLawyerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LawyerTbl;
    private javax.swing.JTextField SCDate;
    private javax.swing.JTextField SCLawyer;
    private javax.swing.JTextField SCName;
    private javax.swing.JTextField SCPayment;
    private javax.swing.JButton aptbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) LawyerTbl.getModel();
        model.setRowCount(0);

        for (SPLawyer lawyer : slawyerDirectory.getAllLawyers()) {
            Object[] row = new Object[]{
                lawyer.getCentralId(),
                lawyer.getName(),
                lawyer.getPhoneNumber(),
                lawyer.getEmail(),
                lawyer.getAddress(),
                lawyer.getConsultationFee()
            };
            model.addRow(row);
        }}
}
