/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Client;

import Modelclass.Appointment;
import Modelclass.AppointmentDirectory;
import Modelclass.ClientDirectory;
import Modelclass.HCLawyer;
import Modelclass.HCLawyerDirectory;
import Modelclass.SPLawyer;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lokes
 */
public class ClientHCLawyerJPanel extends javax.swing.JPanel {
    
     private JPanel workArea;
//    private SPLawyerDirectory slawyerDirectory;
    private AppointmentDirectory appointmentDirectory;
    /**
     * Creates new form LawyerManagementJPanel
     */
    HCLawyerDirectory hlawyerDirectory = new HCLawyerDirectory();

    /**
     * Creates new form ClientHCLawyerJPanel
     */
    public ClientHCLawyerJPanel(JPanel workArea,AppointmentDirectory appointmentDirectory,  HCLawyerDirectory hlawyerDirectory) {
        initComponents();
        this.workArea=workArea;
        hlawyerDirectory = new HCLawyerDirectory();
        populateHighCourtLawyers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aptbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LawyerTbl = new javax.swing.JTable();
        SCLawyer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SCPayment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SCName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SCDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        aptbtn.setText("Book Appointment");
        aptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("High Court Lawyer Appointment");

        LawyerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "State ID", "Name", "Phone Number", "Email", "Office Address", "Consultation Fee"
            }
        ));
        jScrollPane1.setViewportView(LawyerTbl);

        SCLawyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCLawyerActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment");

        jLabel7.setText("Name");

        jLabel3.setText("Date");

        jLabel4.setText("Lawyer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aptbtn)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(236, 236, 236))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(SCName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SCDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SCLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(SCLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aptbtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptbtnActionPerformed
        // TODO add your handling code here:
        String name = SCName.getText();
        String date = SCDate.getText();
        String lawyerName = SCLawyer.getText();
        String payment = SCPayment.getText();

        if (name.isEmpty() || date.isEmpty() || lawyerName.isEmpty() || payment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields.");
            return;
        }

        // Create a new Appointment object
        Appointment newAppointment = new Appointment();
        newAppointment.setName(name);
        newAppointment.setDate(date);
        newAppointment.setLawyer(lawyerName);
        newAppointment.setPayment(payment);

        // Add the appointment to the appointment directory
        appointmentDirectory.getAppointments().add(newAppointment);

        // Optionally, you can also update the table or show a success message
        JOptionPane.showMessageDialog(this, "Appointment booked successfully!");
        ClientFeedBackJPanel panel = new ClientFeedBackJPanel(workArea);
            workArea.add("ClientLoginJPanel", panel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        // Clear the input fields
        SCName.setText("");
        SCDate.setText("");
        SCLawyer.setText("");
        SCPayment.setText("");
    }//GEN-LAST:event_aptbtnActionPerformed

    private void SCLawyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCLawyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCLawyerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LawyerTbl;
    private javax.swing.JTextField SCDate;
    private javax.swing.JTextField SCLawyer;
    private javax.swing.JTextField SCName;
    private javax.swing.JTextField SCPayment;
    private javax.swing.JButton aptbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateHighCourtLawyers() {
       DefaultTableModel model = (DefaultTableModel) LawyerTbl.getModel();
        model.setRowCount(0);

        for (HCLawyer lawyer : hlawyerDirectory.getAllLawyers()) {
            Object[] row = new Object[]{
                lawyer.getStateId(),
                lawyer.getName(),
                lawyer.getPhoneNumber(),
                lawyer.getEmail(),
                lawyer.getAddress(),
                lawyer.getConsultationFee()
            };
            model.addRow(row);
        }}
    
}

