/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Client;

import Modelclass.AppointmentDirectory;
import Modelclass.Client;
import Modelclass.ClientDirectory;
import Modelclass.HCLawyerDirectory;
import Modelclass.SPLawyerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author lokes
 */
public class ClientAppointmentJPanel extends javax.swing.JPanel {
    JPanel workArea;
    Client client;
    ClientDirectory clientDirectory;
    AppointmentDirectory appointmentDirectory;
    HCLawyerDirectory hlawyerDirectory;
    SPLawyerDirectory slawyerDirectory;
//    HCLawyerDirectory hlawyerDirectory;

    /**
     * Creates new form ClientAppointmentJPanel
     */
    public ClientAppointmentJPanel(JPanel workArea) {
        initComponents();
        this.workArea=workArea;
//        this.client=client;
//      
//        this.hlawyerDirectory = hlawyerDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HCbtn = new javax.swing.JButton();
        SCbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        HCbtn.setText("High Court");
        HCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCbtnActionPerformed(evt);
            }
        });

        SCbtn.setText("Supreme Court");
        SCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Book Appointment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HCbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SCbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(106, 106, 106)
                .addComponent(HCbtn)
                .addGap(26, 26, 26)
                .addComponent(SCbtn)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCbtnActionPerformed
        // TODO add your handling code here:
        ClientHCLawyerJPanel panel = new ClientHCLawyerJPanel( workArea, appointmentDirectory,  hlawyerDirectory);
        workArea.add("ClientHCLawyerJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_HCbtnActionPerformed

    private void SCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCbtnActionPerformed
        // TODO add your handling code here:
        ClientSCLawyerJPanel panel = new ClientSCLawyerJPanel(workArea, appointmentDirectory, slawyerDirectory );
        workArea.add("ClientSCLawyerJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_SCbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HCbtn;
    private javax.swing.JButton SCbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
