/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HighCourtLawyer;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Modelclass.HCLawyer;
import Modelclass.HCLawyerDirectory;

/**
 *
 * @author dell
 */
public class HCLawyerLoginJPanel extends javax.swing.JPanel {
   private JPanel workArea;
private HCLawyerDirectory hlawyerDirectory;
    
   
//    HCLawyerDirectory hlawyerDirectory = new HCLawyerDirectory();
    
    
    public HCLawyerLoginJPanel(JPanel workArea, HCLawyerDirectory hlawyerDirectory) {
        initComponents();
        this.workArea = workArea;
        this.hlawyerDirectory = hlawyerDirectory;
        populateLawyerDropdown();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lawyerRolecmb = new javax.swing.JComboBox<>();

        jLabel1.setText("Username :");

        jLabel2.setText("Password : ");

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("High Court Lawyer Login");

        jLabel4.setText("Specialization : ");

        lawyerRolecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lawyerRolecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lawyerRolecmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtpwd))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginbtn)
                            .addComponent(lawyerRolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lawyerRolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginbtn)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
       String username = txtusername.getText().trim();
        String password = new String(txtpwd.getPassword()).trim();
        String specialization = lawyerRolecmb.getSelectedItem().toString();

        if (username.isEmpty() || password.isEmpty() || specialization.equals("Select")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (hlawyerDirectory == null) {
            JOptionPane.showMessageDialog(this, "Lawyer directory is not initialized.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        HCLawyer hcLawyer = hlawyerDirectory.authenticateLawyer(username, password, specialization);

        if (hcLawyer == null) {
            JOptionPane.showMessageDialog(this, "Invalid credentials or specialization.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

            HCLawyerWorkArea dashboardPanel = new HCLawyerWorkArea(workArea, hcLawyer);
            workArea.add("LawyerDashboard", dashboardPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        }
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void lawyerRolecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lawyerRolecmbActionPerformed
        //        AdminRolecmb.removeAllItems();
        //        AdminRolecmb.addItem("Select");
        //        AdminRolecmb.addItem("High Court");
        //        AdminRolecmb.addItem("Supreme Court");
        if (lawyerRolecmb.getSelectedItem() == null) return;

        // Populate the `adminRole` JComboBox with valid role options dynamically
        String selectedRole = lawyerRolecmb.getSelectedItem().toString();

    }//GEN-LAST:event_lawyerRolecmbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> lawyerRolecmb;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
private void populateLawyerDropdown() {
        lawyerRolecmb.removeAllItems();
        lawyerRolecmb.addItem("Select");
        lawyerRolecmb.addItem("Criminal Lawyer");
        lawyerRolecmb.addItem("Civil Lawyer");
        lawyerRolecmb.addItem("Family Lawyer");
        lawyerRolecmb.addItem("Corporate Lawyer");
        
    }
}
