/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import Modelclass.AdminDirectory;
import Modelclass.HCLawyerDirectory;
import Modelclass.SPLawyerDirectory;
import ui.Admin.AdminJPanel;
import ui.HighCourtLawyer.HCLawyerRegisterJPanel;
import ui.HighCourtLawyer.LawyerJPanel;

/**
 *
 * @author dell
 */
public class MainJFrame extends javax.swing.JFrame {
      private AdminDirectory adminDirectory;
      private HCLawyerDirectory hlawyerDirectory;
      private SPLawyerDirectory slawyerDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        adminDirectory = new AdminDirectory();
        hlawyerDirectory = new HCLawyerDirectory();
        slawyerDirectory =new SPLawyerDirectory();
        setSize(830,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        adminbtn = new javax.swing.JButton();
        lawyerbtn = new javax.swing.JButton();
        clientbtn = new javax.swing.JButton();
        forensicbtn = new javax.swing.JButton();
        policebtn = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminbtn.setText("Admin");
        adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnActionPerformed(evt);
            }
        });

        lawyerbtn.setText("Lawyer");
        lawyerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lawyerbtnActionPerformed(evt);
            }
        });

        clientbtn.setText("Client");

        forensicbtn.setText("Forensic");
        forensicbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forensicbtnActionPerformed(evt);
            }
        });

        policebtn.setText("Police");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminbtn)
                    .addComponent(lawyerbtn)
                    .addComponent(clientbtn)
                    .addComponent(forensicbtn)
                    .addComponent(policebtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(adminbtn)
                .addGap(34, 34, 34)
                .addComponent(lawyerbtn)
                .addGap(38, 38, 38)
                .addComponent(clientbtn)
                .addGap(39, 39, 39)
                .addComponent(policebtn)
                .addGap(40, 40, 40)
                .addComponent(forensicbtn)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lawyerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lawyerbtnActionPerformed
        // TODO add your handling code here:
        LawyerJPanel panel = new LawyerJPanel(workArea);
        workArea.add("LawyerJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_lawyerbtnActionPerformed

    private void forensicbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forensicbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forensicbtnActionPerformed

    private void adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnActionPerformed
       AdminJPanel panel = new AdminJPanel(workArea, adminDirectory);
        workArea.add("AdminiJPanel", panel);
        CardLayout layout =(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_adminbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn;
    private javax.swing.JButton clientbtn;
    private javax.swing.JButton forensicbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton lawyerbtn;
    private javax.swing.JButton policebtn;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
